// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/beefy/v1/beefy.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RelayChain int32

const (
	RelayChain_POLKADOT RelayChain = 0
	RelayChain_KUSAMA   RelayChain = 1
	RelayChain_ROCOCO   RelayChain = 2
)

var RelayChain_name = map[int32]string{
	0: "POLKADOT",
	1: "KUSAMA",
	2: "ROCOCO",
}

var RelayChain_value = map[string]int32{
	"POLKADOT": 0,
	"KUSAMA":   1,
	"ROCOCO":   2,
}

func (x RelayChain) String() string {
	return proto.EnumName(RelayChain_name, int32(x))
}

func (RelayChain) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{0}
}

// ClientState from Beefy tracks the current validator set, latest height,
// and a possible frozen height.
type ClientState struct {
	// Latest mmr root hash
	MmrRootHash []byte `protobuf:"bytes,1,opt,name=mmr_root_hash,json=mmrRootHash,proto3" json:"mmr_root_hash,omitempty"`
	// block number for the latest mmr_root_hash
	LatestBeefyHeight uint32 `protobuf:"varint,2,opt,name=latest_beefy_height,json=latestBeefyHeight,proto3" json:"latest_beefy_height,omitempty"`
	// Block height when the client was frozen due to a misbehaviour
	FrozenHeight uint64 `protobuf:"varint,3,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	/// Known relay chains
	RelayChain RelayChain `protobuf:"varint,4,opt,name=relay_chain,json=relayChain,proto3,enum=ibc.lightclients.beefy.v1.RelayChain" json:"relay_chain,omitempty"`
	/// ParaId of associated parachain
	ParaId uint32 `protobuf:"varint,5,opt,name=para_id,json=paraId,proto3" json:"para_id,omitempty"`
	/// latest parachain height
	LatestParaHeight uint32 `protobuf:"varint,6,opt,name=latest_para_height,json=latestParaHeight,proto3" json:"latest_para_height,omitempty"`
	// block number that the beefy protocol was activated on the relay chain.
	// This should be the first block in the merkle-mountain-range tree.
	BeefyActivationBlock uint32 `protobuf:"varint,7,opt,name=beefy_activation_block,json=beefyActivationBlock,proto3" json:"beefy_activation_block,omitempty"`
	// authorities for the current round
	Authority *BeefyAuthoritySet `protobuf:"bytes,8,opt,name=authority,proto3" json:"authority,omitempty"`
	// authorities for the next round
	NextAuthoritySet *BeefyAuthoritySet `protobuf:"bytes,9,opt,name=next_authority_set,json=nextAuthoritySet,proto3" json:"next_authority_set,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{0}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientState.Unmarshal(m, b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return xxx_messageInfo_ClientState.Size(m)
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

// Actual payload items
type PayloadItem struct {
	// 2-byte payload id
	PayloadId *SizedByte2 `protobuf:"bytes,1,opt,name=payload_id,json=payloadId,proto3,customtype=SizedByte2" json:"payload_id,omitempty"`
	// arbitrary length payload data., eg mmr_root_hash
	PayloadData []byte `protobuf:"bytes,2,opt,name=payload_data,json=payloadData,proto3" json:"payload_data,omitempty"`
}

func (m *PayloadItem) Reset()         { *m = PayloadItem{} }
func (m *PayloadItem) String() string { return proto.CompactTextString(m) }
func (*PayloadItem) ProtoMessage()    {}
func (*PayloadItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{1}
}
func (m *PayloadItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadItem.Unmarshal(m, b)
}
func (m *PayloadItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadItem.Marshal(b, m, deterministic)
}
func (m *PayloadItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadItem.Merge(m, src)
}
func (m *PayloadItem) XXX_Size() int {
	return xxx_messageInfo_PayloadItem.Size(m)
}
func (m *PayloadItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadItem.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadItem proto.InternalMessageInfo

// Commitment message signed by beefy validators
type Commitment struct {
	// array of payload items signed by Beefy validators
	Payload []*PayloadItem `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
	// block number for this commitment
	BlockNumer uint32 `protobuf:"varint,2,opt,name=block_numer,json=blockNumer,proto3" json:"block_numer,omitempty"`
	// validator set that signed this commitment
	ValidatorSetId uint64 `protobuf:"varint,3,opt,name=validator_set_id,json=validatorSetId,proto3" json:"validator_set_id,omitempty"`
}

func (m *Commitment) Reset()         { *m = Commitment{} }
func (m *Commitment) String() string { return proto.CompactTextString(m) }
func (*Commitment) ProtoMessage()    {}
func (*Commitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{2}
}
func (m *Commitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commitment.Unmarshal(m, b)
}
func (m *Commitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commitment.Marshal(b, m, deterministic)
}
func (m *Commitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commitment.Merge(m, src)
}
func (m *Commitment) XXX_Size() int {
	return xxx_messageInfo_Commitment.Size(m)
}
func (m *Commitment) XXX_DiscardUnknown() {
	xxx_messageInfo_Commitment.DiscardUnknown(m)
}

var xxx_messageInfo_Commitment proto.InternalMessageInfo

// Signature belonging to a single validator
type CommitmentSignature struct {
	// actual signature bytes
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// authority leaf index in the merkle tree.
	AuthorityIndex uint32 `protobuf:"varint,2,opt,name=authority_index,json=authorityIndex,proto3" json:"authority_index,omitempty"`
}

func (m *CommitmentSignature) Reset()         { *m = CommitmentSignature{} }
func (m *CommitmentSignature) String() string { return proto.CompactTextString(m) }
func (*CommitmentSignature) ProtoMessage()    {}
func (*CommitmentSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{3}
}
func (m *CommitmentSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitmentSignature.Unmarshal(m, b)
}
func (m *CommitmentSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitmentSignature.Marshal(b, m, deterministic)
}
func (m *CommitmentSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitmentSignature.Merge(m, src)
}
func (m *CommitmentSignature) XXX_Size() int {
	return xxx_messageInfo_CommitmentSignature.Size(m)
}
func (m *CommitmentSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitmentSignature.DiscardUnknown(m)
}

var xxx_messageInfo_CommitmentSignature proto.InternalMessageInfo

// signed commitment data
type SignedCommitment struct {
	// commitment data being signed
	Commitment *Commitment `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// gotten from rpc subscription
	Signatures []*CommitmentSignature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *SignedCommitment) Reset()         { *m = SignedCommitment{} }
func (m *SignedCommitment) String() string { return proto.CompactTextString(m) }
func (*SignedCommitment) ProtoMessage()    {}
func (*SignedCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{4}
}
func (m *SignedCommitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedCommitment.Unmarshal(m, b)
}
func (m *SignedCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedCommitment.Marshal(b, m, deterministic)
}
func (m *SignedCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedCommitment.Merge(m, src)
}
func (m *SignedCommitment) XXX_Size() int {
	return xxx_messageInfo_SignedCommitment.Size(m)
}
func (m *SignedCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_SignedCommitment proto.InternalMessageInfo

// data needed to update the client
type ClientStateUpdateProof struct {
	// the new mmr leaf SCALE encoded.
	MmrLeaf *BeefyMmrLeaf `protobuf:"bytes,1,opt,name=mmr_leaf,json=mmrLeaf,proto3" json:"mmr_leaf,omitempty"`
	// leaf index for the mmr_leaf
	MmrLeafIndex uint64 `protobuf:"varint,2,opt,name=mmr_leaf_index,json=mmrLeafIndex,proto3" json:"mmr_leaf_index,omitempty"`
	// proof that this mmr_leaf index is valid.
	MmrProof [][]byte `protobuf:"bytes,3,rep,name=mmr_proof,json=mmrProof,proto3" json:"mmr_proof,omitempty"`
	// signed commitment data
	SignedCommitment *SignedCommitment `protobuf:"bytes,4,opt,name=signed_commitment,json=signedCommitment,proto3" json:"signed_commitment,omitempty"`
	// generated using full authority list from runtime
	AuthoritiesProof [][]byte `protobuf:"bytes,5,rep,name=authorities_proof,json=authoritiesProof,proto3" json:"authorities_proof,omitempty"`
}

func (m *ClientStateUpdateProof) Reset()         { *m = ClientStateUpdateProof{} }
func (m *ClientStateUpdateProof) String() string { return proto.CompactTextString(m) }
func (*ClientStateUpdateProof) ProtoMessage()    {}
func (*ClientStateUpdateProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{5}
}
func (m *ClientStateUpdateProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStateUpdateProof.Unmarshal(m, b)
}
func (m *ClientStateUpdateProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStateUpdateProof.Marshal(b, m, deterministic)
}
func (m *ClientStateUpdateProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStateUpdateProof.Merge(m, src)
}
func (m *ClientStateUpdateProof) XXX_Size() int {
	return xxx_messageInfo_ClientStateUpdateProof.Size(m)
}
func (m *ClientStateUpdateProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStateUpdateProof.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStateUpdateProof proto.InternalMessageInfo

// ConsensusState defines the consensus state from Tendermint.
type ConsensusState struct {
	// timestamp that corresponds to the block height in which the ConsensusState
	// was stored.
	Timestamp time.Time `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	// packet commitment root
	Root []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{6}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusState.Unmarshal(m, b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return xxx_messageInfo_ConsensusState.Size(m)
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

// Misbehaviour is a wrapper over two conflicting Headers
// that implements Misbehaviour interface expected by ICS-02
type Misbehaviour struct {
	Header1 *Header `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty" yaml:"header_1"`
	Header2 *Header `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty" yaml:"header_2"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{7}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Misbehaviour.Unmarshal(m, b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return xxx_messageInfo_Misbehaviour.Size(m)
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

// Header contains the neccessary data to prove finality about IBC commitments
type Header struct {
	// optional payload to update ConsensusState
	ConsensusStateUpdate *ConsensusStateUpdateProof `protobuf:"bytes,1,opt,name=consensus_state_update,json=consensusStateUpdate,proto3" json:"consensus_state_update,omitempty"`
	// optional payload to update the ClientState.
	ClientState *ClientStateUpdateProof `protobuf:"bytes,2,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{8}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

/// Parachain headers and their mmr proofs.
type ConsensusStateUpdateProof struct {
	// parachain headers needed for proofs and ConsensusState
	ParachainHeaders []*ParachainHeader `protobuf:"bytes,1,rep,name=parachain_headers,json=parachainHeaders,proto3" json:"parachain_headers,omitempty"`
	// mmr proofs for the headers gotten from rpc "mmr_generateProofs"
	MmrProofs [][]byte `protobuf:"bytes,2,rep,name=mmr_proofs,json=mmrProofs,proto3" json:"mmr_proofs,omitempty"`
	// size of the mmr for the given proof
	MmrSize uint64 `protobuf:"varint,3,opt,name=mmr_size,json=mmrSize,proto3" json:"mmr_size,omitempty"`
}

func (m *ConsensusStateUpdateProof) Reset()         { *m = ConsensusStateUpdateProof{} }
func (m *ConsensusStateUpdateProof) String() string { return proto.CompactTextString(m) }
func (*ConsensusStateUpdateProof) ProtoMessage()    {}
func (*ConsensusStateUpdateProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{9}
}
func (m *ConsensusStateUpdateProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusStateUpdateProof.Unmarshal(m, b)
}
func (m *ConsensusStateUpdateProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusStateUpdateProof.Marshal(b, m, deterministic)
}
func (m *ConsensusStateUpdateProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusStateUpdateProof.Merge(m, src)
}
func (m *ConsensusStateUpdateProof) XXX_Size() int {
	return xxx_messageInfo_ConsensusStateUpdateProof.Size(m)
}
func (m *ConsensusStateUpdateProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusStateUpdateProof.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusStateUpdateProof proto.InternalMessageInfo

func (m *ConsensusStateUpdateProof) GetParachainHeaders() []*ParachainHeader {
	if m != nil {
		return m.ParachainHeaders
	}
	return nil
}

func (m *ConsensusStateUpdateProof) GetMmrProofs() [][]byte {
	if m != nil {
		return m.MmrProofs
	}
	return nil
}

func (m *ConsensusStateUpdateProof) GetMmrSize() uint64 {
	if m != nil {
		return m.MmrSize
	}
	return 0
}

// data needed to prove parachain header inclusion in mmr.
type ParachainHeader struct {
	// scale-encoded parachain header bytes
	ParachainHeader []byte `protobuf:"bytes,1,opt,name=parachain_header,json=parachainHeader,proto3" json:"parachain_header,omitempty"`
	// see beefy spec
	MmrLeafPartial *BeefyMmrLeafPartial `protobuf:"bytes,2,opt,name=mmr_leaf_partial,json=mmrLeafPartial,proto3" json:"mmr_leaf_partial,omitempty"`
	// proofs for our header in the parachain heads root
	ParachainHeadsProof [][]byte `protobuf:"bytes,3,rep,name=parachain_heads_proof,json=parachainHeadsProof,proto3" json:"parachain_heads_proof,omitempty"`
	// leaf index for parachain heads proof
	HeadsLeafIndex uint32 `protobuf:"varint,4,opt,name=heads_leaf_index,json=headsLeafIndex,proto3" json:"heads_leaf_index,omitempty"`
	// total number of para heads in parachain_heads_root
	HeadsTotalCount uint32 `protobuf:"varint,5,opt,name=heads_total_count,json=headsTotalCount,proto3" json:"heads_total_count,omitempty"`
	// trie merkle proof of inclusion in header.extrinsic_root
	ExtrinsicProof [][]byte `protobuf:"bytes,6,rep,name=extrinsic_proof,json=extrinsicProof,proto3" json:"extrinsic_proof,omitempty"`
	// the actual timestamp extrinsic
	TimestampExtrinsic []byte `protobuf:"bytes,7,opt,name=timestamp_extrinsic,json=timestampExtrinsic,proto3" json:"timestamp_extrinsic,omitempty"`
}

func (m *ParachainHeader) Reset()         { *m = ParachainHeader{} }
func (m *ParachainHeader) String() string { return proto.CompactTextString(m) }
func (*ParachainHeader) ProtoMessage()    {}
func (*ParachainHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{10}
}
func (m *ParachainHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParachainHeader.Unmarshal(m, b)
}
func (m *ParachainHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParachainHeader.Marshal(b, m, deterministic)
}
func (m *ParachainHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParachainHeader.Merge(m, src)
}
func (m *ParachainHeader) XXX_Size() int {
	return xxx_messageInfo_ParachainHeader.Size(m)
}
func (m *ParachainHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ParachainHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ParachainHeader proto.InternalMessageInfo

// Partial data for MmrLeaf
type BeefyMmrLeafPartial struct {
	// leaf version
	Version U8 `protobuf:"varint,1,opt,name=version,proto3,customtype=U8" json:"version"`
	// parent block for this leaf
	ParentNumber uint32 `protobuf:"varint,2,opt,name=parent_number,json=parentNumber,proto3" json:"parent_number,omitempty"`
	// parent hash for this leaf
	ParentHash *SizedByte32 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3,customtype=SizedByte32" json:"parent_hash,omitempty"`
	// next authority set.
	BeefyNextAuthoritySet BeefyAuthoritySet `protobuf:"bytes,4,opt,name=beefy_next_authority_set,json=beefyNextAuthoritySet,proto3" json:"beefy_next_authority_set"`
}

func (m *BeefyMmrLeafPartial) Reset()         { *m = BeefyMmrLeafPartial{} }
func (m *BeefyMmrLeafPartial) String() string { return proto.CompactTextString(m) }
func (*BeefyMmrLeafPartial) ProtoMessage()    {}
func (*BeefyMmrLeafPartial) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{11}
}
func (m *BeefyMmrLeafPartial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeefyMmrLeafPartial.Unmarshal(m, b)
}
func (m *BeefyMmrLeafPartial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeefyMmrLeafPartial.Marshal(b, m, deterministic)
}
func (m *BeefyMmrLeafPartial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeefyMmrLeafPartial.Merge(m, src)
}
func (m *BeefyMmrLeafPartial) XXX_Size() int {
	return xxx_messageInfo_BeefyMmrLeafPartial.Size(m)
}
func (m *BeefyMmrLeafPartial) XXX_DiscardUnknown() {
	xxx_messageInfo_BeefyMmrLeafPartial.DiscardUnknown(m)
}

var xxx_messageInfo_BeefyMmrLeafPartial proto.InternalMessageInfo

// Beefy Authority Info
type BeefyAuthoritySet struct {
	// Id of the authority set, it should be strictly increasing
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// size of the authority set
	Len uint32 `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	// merkle root of the sorted authority public keys.
	AuthorityRoot *SizedByte32 `protobuf:"bytes,3,opt,name=authority_root,json=authorityRoot,proto3,customtype=SizedByte32" json:"authority_root,omitempty"`
}

func (m *BeefyAuthoritySet) Reset()         { *m = BeefyAuthoritySet{} }
func (m *BeefyAuthoritySet) String() string { return proto.CompactTextString(m) }
func (*BeefyAuthoritySet) ProtoMessage()    {}
func (*BeefyAuthoritySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{12}
}
func (m *BeefyAuthoritySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeefyAuthoritySet.Unmarshal(m, b)
}
func (m *BeefyAuthoritySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeefyAuthoritySet.Marshal(b, m, deterministic)
}
func (m *BeefyAuthoritySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeefyAuthoritySet.Merge(m, src)
}
func (m *BeefyAuthoritySet) XXX_Size() int {
	return xxx_messageInfo_BeefyAuthoritySet.Size(m)
}
func (m *BeefyAuthoritySet) XXX_DiscardUnknown() {
	xxx_messageInfo_BeefyAuthoritySet.DiscardUnknown(m)
}

var xxx_messageInfo_BeefyAuthoritySet proto.InternalMessageInfo

// BeefyMmrLeaf leaf data
type BeefyMmrLeaf struct {
	// leaf version
	Version U8 `protobuf:"varint,1,opt,name=version,proto3,customtype=U8" json:"version"`
	// parent block for this leaf
	ParentNumber uint32 `protobuf:"varint,2,opt,name=parent_number,json=parentNumber,proto3" json:"parent_number,omitempty"`
	// parent hash for this leaf
	ParentHash *SizedByte32 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3,customtype=SizedByte32" json:"parent_hash,omitempty"`
	// beefy next authority set.
	BeefyNextAuthoritySet BeefyAuthoritySet `protobuf:"bytes,4,opt,name=beefy_next_authority_set,json=beefyNextAuthoritySet,proto3" json:"beefy_next_authority_set"`
	// merkle root hash of parachain heads included in the leaf.
	ParachainHeads *SizedByte32 `protobuf:"bytes,5,opt,name=parachain_heads,json=parachainHeads,proto3,customtype=SizedByte32" json:"parachain_heads,omitempty"`
}

func (m *BeefyMmrLeaf) Reset()         { *m = BeefyMmrLeaf{} }
func (m *BeefyMmrLeaf) String() string { return proto.CompactTextString(m) }
func (*BeefyMmrLeaf) ProtoMessage()    {}
func (*BeefyMmrLeaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_43205c4bfbe9a422, []int{13}
}
func (m *BeefyMmrLeaf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeefyMmrLeaf.Unmarshal(m, b)
}
func (m *BeefyMmrLeaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeefyMmrLeaf.Marshal(b, m, deterministic)
}
func (m *BeefyMmrLeaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeefyMmrLeaf.Merge(m, src)
}
func (m *BeefyMmrLeaf) XXX_Size() int {
	return xxx_messageInfo_BeefyMmrLeaf.Size(m)
}
func (m *BeefyMmrLeaf) XXX_DiscardUnknown() {
	xxx_messageInfo_BeefyMmrLeaf.DiscardUnknown(m)
}

var xxx_messageInfo_BeefyMmrLeaf proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("ibc.lightclients.beefy.v1.RelayChain", RelayChain_name, RelayChain_value)
	golang_proto.RegisterEnum("ibc.lightclients.beefy.v1.RelayChain", RelayChain_name, RelayChain_value)
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.beefy.v1.ClientState")
	golang_proto.RegisterType((*ClientState)(nil), "ibc.lightclients.beefy.v1.ClientState")
	proto.RegisterType((*PayloadItem)(nil), "ibc.lightclients.beefy.v1.PayloadItem")
	golang_proto.RegisterType((*PayloadItem)(nil), "ibc.lightclients.beefy.v1.PayloadItem")
	proto.RegisterType((*Commitment)(nil), "ibc.lightclients.beefy.v1.Commitment")
	golang_proto.RegisterType((*Commitment)(nil), "ibc.lightclients.beefy.v1.Commitment")
	proto.RegisterType((*CommitmentSignature)(nil), "ibc.lightclients.beefy.v1.CommitmentSignature")
	golang_proto.RegisterType((*CommitmentSignature)(nil), "ibc.lightclients.beefy.v1.CommitmentSignature")
	proto.RegisterType((*SignedCommitment)(nil), "ibc.lightclients.beefy.v1.SignedCommitment")
	golang_proto.RegisterType((*SignedCommitment)(nil), "ibc.lightclients.beefy.v1.SignedCommitment")
	proto.RegisterType((*ClientStateUpdateProof)(nil), "ibc.lightclients.beefy.v1.ClientStateUpdateProof")
	golang_proto.RegisterType((*ClientStateUpdateProof)(nil), "ibc.lightclients.beefy.v1.ClientStateUpdateProof")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.beefy.v1.ConsensusState")
	golang_proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.beefy.v1.ConsensusState")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.beefy.v1.Misbehaviour")
	golang_proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.beefy.v1.Misbehaviour")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.beefy.v1.Header")
	golang_proto.RegisterType((*Header)(nil), "ibc.lightclients.beefy.v1.Header")
	proto.RegisterType((*ConsensusStateUpdateProof)(nil), "ibc.lightclients.beefy.v1.ConsensusStateUpdateProof")
	golang_proto.RegisterType((*ConsensusStateUpdateProof)(nil), "ibc.lightclients.beefy.v1.ConsensusStateUpdateProof")
	proto.RegisterType((*ParachainHeader)(nil), "ibc.lightclients.beefy.v1.ParachainHeader")
	golang_proto.RegisterType((*ParachainHeader)(nil), "ibc.lightclients.beefy.v1.ParachainHeader")
	proto.RegisterType((*BeefyMmrLeafPartial)(nil), "ibc.lightclients.beefy.v1.BeefyMmrLeafPartial")
	golang_proto.RegisterType((*BeefyMmrLeafPartial)(nil), "ibc.lightclients.beefy.v1.BeefyMmrLeafPartial")
	proto.RegisterType((*BeefyAuthoritySet)(nil), "ibc.lightclients.beefy.v1.BeefyAuthoritySet")
	golang_proto.RegisterType((*BeefyAuthoritySet)(nil), "ibc.lightclients.beefy.v1.BeefyAuthoritySet")
	proto.RegisterType((*BeefyMmrLeaf)(nil), "ibc.lightclients.beefy.v1.BeefyMmrLeaf")
	golang_proto.RegisterType((*BeefyMmrLeaf)(nil), "ibc.lightclients.beefy.v1.BeefyMmrLeaf")
}

func init() {
	proto.RegisterFile("ibc/lightclients/beefy/v1/beefy.proto", fileDescriptor_43205c4bfbe9a422)
}
func init() {
	golang_proto.RegisterFile("ibc/lightclients/beefy/v1/beefy.proto", fileDescriptor_43205c4bfbe9a422)
}

var fileDescriptor_43205c4bfbe9a422 = []byte{
	// 1385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x57, 0x4f, 0x6f, 0x13, 0x47,
	0x14, 0xf7, 0xda, 0x26, 0x7f, 0x9e, 0x1d, 0xc7, 0x99, 0x00, 0x35, 0xb4, 0xb5, 0x43, 0x0a, 0xc5,
	0x05, 0x62, 0xd7, 0x06, 0x55, 0x88, 0x13, 0x71, 0xa0, 0x22, 0x05, 0x92, 0x68, 0x02, 0x2a, 0x42,
	0x95, 0x56, 0xe3, 0xdd, 0x89, 0xbd, 0x62, 0x77, 0xc7, 0xda, 0x19, 0x47, 0x84, 0x53, 0x2f, 0x95,
	0x7a, 0xe4, 0x1b, 0x94, 0x0f, 0x50, 0xb5, 0xd7, 0x1e, 0x7b, 0xe4, 0xc8, 0xb1, 0x42, 0x95, 0x5b,
	0x25, 0xdf, 0xa0, 0xb7, 0xde, 0xaa, 0xf9, 0xb3, 0xeb, 0x4d, 0x08, 0x2e, 0xf4, 0xda, 0xdb, 0xec,
	0x7b, 0xbf, 0x79, 0xef, 0x37, 0xbf, 0x99, 0xf7, 0x66, 0x16, 0x2e, 0x78, 0x5d, 0xa7, 0xe9, 0x7b,
	0xbd, 0xbe, 0x70, 0x7c, 0x8f, 0x86, 0x82, 0x37, 0xbb, 0x94, 0xee, 0xec, 0x35, 0x77, 0x5b, 0x7a,
	0xd0, 0x18, 0x44, 0x4c, 0x30, 0x74, 0xc6, 0xeb, 0x3a, 0x8d, 0x34, 0xac, 0xa1, 0xbd, 0xbb, 0xad,
	0xb3, 0xb5, 0x1e, 0x63, 0x3d, 0x9f, 0x36, 0x15, 0xb0, 0x3b, 0xdc, 0x69, 0x0a, 0x2f, 0xa0, 0x5c,
	0x90, 0x60, 0xa0, 0xe7, 0x9e, 0x3d, 0xd9, 0x63, 0x3d, 0xa6, 0x86, 0x4d, 0x39, 0xd2, 0xd6, 0xe5,
	0xbf, 0x73, 0x50, 0x58, 0x53, 0xb1, 0xb6, 0x05, 0x11, 0x14, 0x2d, 0xc3, 0x5c, 0x10, 0x44, 0x76,
	0xc4, 0x98, 0xb0, 0xfb, 0x84, 0xf7, 0x2b, 0xd6, 0x92, 0x55, 0x2f, 0xe2, 0x42, 0x10, 0x44, 0x98,
	0x31, 0x71, 0x87, 0xf0, 0x3e, 0x6a, 0xc0, 0xa2, 0x4f, 0x04, 0xe5, 0xc2, 0x56, 0xd9, 0xed, 0x3e,
	0x95, 0x8c, 0x2a, 0xd9, 0x25, 0xab, 0x3e, 0x87, 0x17, 0xb4, 0xab, 0x23, 0x3d, 0x77, 0x94, 0x03,
	0x7d, 0x02, 0x73, 0x3b, 0x11, 0x7b, 0x46, 0xc3, 0x18, 0x99, 0x5b, 0xb2, 0xea, 0x79, 0x5c, 0xd4,
	0x46, 0x03, 0xfa, 0x12, 0x0a, 0x11, 0xf5, 0xc9, 0x9e, 0xed, 0xf4, 0x89, 0x17, 0x56, 0xf2, 0x4b,
	0x56, 0xbd, 0xd4, 0xbe, 0xd0, 0x78, 0xeb, 0x82, 0x1b, 0x58, 0xa2, 0xd7, 0x24, 0x18, 0x43, 0x94,
	0x8c, 0xd1, 0x07, 0x30, 0x3d, 0x20, 0x11, 0xb1, 0x3d, 0xb7, 0x72, 0x42, 0x11, 0x9a, 0x92, 0x9f,
	0xeb, 0x2e, 0xba, 0x02, 0xc8, 0xb0, 0x56, 0x7e, 0x43, 0x65, 0x4a, 0x61, 0xca, 0xda, 0xb3, 0x45,
	0x22, 0x62, 0xe8, 0x5c, 0x83, 0xd3, 0x7a, 0x71, 0xc4, 0x11, 0xde, 0x2e, 0x11, 0x1e, 0x0b, 0xed,
	0xae, 0xcf, 0x9c, 0x27, 0x95, 0x69, 0x35, 0xe3, 0xa4, 0xf2, 0xae, 0x26, 0xce, 0x8e, 0xf4, 0xa1,
	0xaf, 0x60, 0x96, 0x0c, 0x45, 0x9f, 0x45, 0x9e, 0xd8, 0xab, 0xcc, 0x2c, 0x59, 0xf5, 0x42, 0xfb,
	0xca, 0x84, 0x25, 0x28, 0x91, 0x56, 0xe3, 0x09, 0xdb, 0x54, 0xe0, 0xf1, 0x74, 0xf4, 0x18, 0x50,
	0x48, 0x9f, 0x0a, 0x3b, 0xb1, 0xd8, 0x9c, 0x8a, 0xca, 0xec, 0x7f, 0x08, 0x5a, 0x96, 0x71, 0xd2,
	0x96, 0x1b, 0xf9, 0xef, 0x5f, 0xd4, 0x32, 0xcb, 0x14, 0x0a, 0x5b, 0x64, 0xcf, 0x67, 0xc4, 0x5d,
	0x17, 0x34, 0x40, 0x2b, 0x00, 0x03, 0xfd, 0x29, 0xc5, 0x53, 0xfb, 0xde, 0x29, 0xbd, 0x1e, 0xd5,
	0x60, 0xdb, 0x7b, 0x46, 0xdd, 0xce, 0x9e, 0xa0, 0x6d, 0x3c, 0x6b, 0x10, 0xeb, 0x2e, 0x3a, 0x07,
	0xc5, 0x18, 0xee, 0x12, 0x41, 0xd4, 0xf6, 0x17, 0x71, 0xc1, 0xd8, 0x6e, 0x11, 0x41, 0x4c, 0x9a,
	0x1f, 0x2c, 0x80, 0x35, 0x16, 0x04, 0x9e, 0x08, 0x68, 0x28, 0xd0, 0x4d, 0xb9, 0x41, 0x0a, 0x53,
	0xb1, 0x96, 0x72, 0xf5, 0x42, 0xfb, 0xd3, 0x09, 0x8b, 0x49, 0xf1, 0xc3, 0xf1, 0x34, 0x54, 0x83,
	0x82, 0xda, 0x0a, 0x3b, 0x1c, 0x06, 0x34, 0x32, 0xe7, 0x0e, 0x94, 0x69, 0x43, 0x5a, 0x50, 0x1d,
	0xca, 0xbb, 0xc4, 0xf7, 0x5c, 0x22, 0x58, 0x24, 0x55, 0x93, 0xeb, 0xd1, 0x67, 0xae, 0x94, 0xd8,
	0xb7, 0xa9, 0x58, 0x77, 0x0d, 0xc3, 0x2e, 0x2c, 0x8e, 0x09, 0x6e, 0x7b, 0xbd, 0x90, 0x88, 0x61,
	0x44, 0xd1, 0x47, 0x30, 0xcb, 0xe3, 0x0f, 0x53, 0x07, 0x63, 0x03, 0xba, 0x08, 0xf3, 0xe3, 0xad,
	0xf1, 0x42, 0x97, 0x3e, 0x35, 0x4c, 0x4a, 0x89, 0x79, 0x5d, 0x5a, 0x4d, 0x8e, 0x9f, 0x2d, 0x28,
	0xcb, 0xd0, 0xd4, 0x4d, 0x69, 0x71, 0x1b, 0xc0, 0x49, 0xbe, 0x54, 0x8a, 0xc2, 0xc4, 0x33, 0x3f,
	0x9e, 0x8a, 0x53, 0x13, 0xd1, 0x06, 0x40, 0xc2, 0x8b, 0x57, 0xb2, 0x4a, 0xd5, 0xc6, 0x3b, 0x85,
	0x49, 0x16, 0x8b, 0x53, 0x11, 0x0c, 0xe3, 0x1f, 0xb3, 0x70, 0x3a, 0xd5, 0x1a, 0x1e, 0x0e, 0x5c,
	0x22, 0xe8, 0x56, 0xc4, 0xd8, 0x0e, 0xea, 0xc0, 0x8c, 0xec, 0x12, 0x3e, 0x25, 0x3b, 0x86, 0xf5,
	0xc5, 0x7f, 0x3b, 0x91, 0xf7, 0x83, 0xe8, 0x1e, 0x25, 0x3b, 0x78, 0x3a, 0xd0, 0x03, 0x74, 0x1e,
	0x4a, 0x71, 0x8c, 0x94, 0x7c, 0x79, 0x5c, 0x34, 0x00, 0x25, 0x1e, 0xfa, 0x10, 0x66, 0x25, 0x6a,
	0x20, 0xd3, 0x56, 0x72, 0x4b, 0xb9, 0x7a, 0x11, 0xcb, 0xd4, 0x9a, 0xc6, 0x23, 0x58, 0xe0, 0x4a,
	0x52, 0x3b, 0xa5, 0x62, 0x5e, 0xf1, 0xb9, 0x3c, 0x81, 0xcf, 0xd1, 0x6d, 0xc0, 0x65, 0x7e, 0x74,
	0x63, 0x2e, 0xc3, 0x42, 0xbc, 0x8b, 0x1e, 0xe5, 0x26, 0xfd, 0x09, 0x95, 0xbe, 0x9c, 0x72, 0x28,
	0x1a, 0x46, 0xae, 0x10, 0x4a, 0x6b, 0x2c, 0xe4, 0x34, 0xe4, 0x43, 0xae, 0x7b, 0x69, 0x07, 0x66,
	0x93, 0x26, 0x6c, 0x64, 0x3a, 0xdb, 0xd0, 0x6d, 0xba, 0x11, 0xb7, 0xe9, 0xc6, 0x83, 0x18, 0xd1,
	0x99, 0x79, 0x39, 0xaa, 0x65, 0x9e, 0xff, 0x51, 0xb3, 0xf0, 0x78, 0x1a, 0x42, 0x90, 0x97, 0xbd,
	0xd8, 0x54, 0x97, 0x1a, 0x9b, 0x7c, 0xaf, 0x2c, 0x28, 0xde, 0xf7, 0x78, 0x97, 0xf6, 0xc9, 0xae,
	0xc7, 0x86, 0x11, 0xfa, 0x06, 0x66, 0xfa, 0x94, 0xb8, 0x34, 0xb2, 0x5b, 0x0a, 0x5e, 0x68, 0x9f,
	0x9b, 0x20, 0xc2, 0x1d, 0x05, 0xed, 0x54, 0xf7, 0x47, 0xb5, 0x69, 0x3d, 0x6e, 0xfd, 0x35, 0xaa,
	0xcd, 0xef, 0x91, 0xc0, 0xbf, 0xb1, 0x1c, 0xc7, 0x59, 0xc6, 0xd3, 0x7a, 0xd8, 0x4a, 0x45, 0x6f,
	0xab, 0x5a, 0x7a, 0xdf, 0xe8, 0xed, 0x37, 0xa2, 0xb7, 0x93, 0xe8, 0x6d, 0xb3, 0xa4, 0xdf, 0x2d,
	0x98, 0xd2, 0x68, 0x34, 0x80, 0xd3, 0x4e, 0xac, 0xa6, 0xcd, 0xa5, 0x9c, 0xf6, 0x50, 0x1d, 0x40,
	0x23, 0xe4, 0xb5, 0x89, 0xc7, 0x3b, 0xbd, 0x0d, 0xa9, 0x73, 0xdb, 0xc9, 0xbf, 0x1c, 0xd5, 0x2c,
	0x7c, 0xd2, 0x39, 0x06, 0x80, 0x1e, 0x43, 0x51, 0x47, 0xd2, 0xe9, 0x8c, 0x84, 0xad, 0x49, 0x79,
	0x8e, 0x2d, 0x0e, 0x93, 0xa4, 0xe0, 0x8c, 0xbd, 0x66, 0x79, 0x3f, 0x59, 0x70, 0xe6, 0xad, 0xdc,
	0xd0, 0xd7, 0xb0, 0x20, 0x2f, 0x26, 0x75, 0xfd, 0xd9, 0x5a, 0x17, 0x6e, 0x3a, 0xe4, 0xa5, 0x89,
	0x1d, 0xd2, 0xcc, 0xd1, 0xc2, 0xe1, 0xf2, 0xe0, 0xb0, 0x81, 0xa3, 0x8f, 0x01, 0x92, 0x12, 0xd2,
	0xdd, 0xa1, 0x88, 0x67, 0xe3, 0x1a, 0xe2, 0xe8, 0x8c, 0xae, 0x65, 0xee, 0x3d, 0xa3, 0xa6, 0x49,
	0xca, 0x12, 0x95, 0x3d, 0x7f, 0xf9, 0xdb, 0x1c, 0xcc, 0x1f, 0x89, 0x8f, 0x3e, 0x83, 0xf2, 0x51,
	0x9a, 0xa6, 0x37, 0xce, 0x1f, 0xc9, 0x8c, 0x1e, 0x41, 0x39, 0xa9, 0xf0, 0x01, 0x89, 0x84, 0x47,
	0x7c, 0xa3, 0x6a, 0xe3, 0x1d, 0xbb, 0xc5, 0x96, 0x9e, 0x85, 0x4b, 0xc1, 0xa1, 0x6f, 0xd4, 0x86,
	0x53, 0x87, 0x49, 0xf0, 0x43, 0x1d, 0x62, 0xf1, 0x10, 0x13, 0x5d, 0xa5, 0xf2, 0x52, 0xd0, 0xc8,
	0x54, 0xc7, 0xc9, 0xeb, 0x86, 0xad, 0xec, 0xe3, 0x9e, 0x73, 0x09, 0x16, 0x34, 0x52, 0x30, 0x41,
	0x7c, 0xdb, 0x61, 0xc3, 0x50, 0x98, 0xc7, 0xc4, 0xbc, 0x72, 0x3c, 0x90, 0xf6, 0x35, 0x69, 0x96,
	0xb7, 0x00, 0x7d, 0x2a, 0x22, 0x2f, 0xe4, 0x9e, 0x63, 0x38, 0x4c, 0x29, 0x0e, 0xa5, 0xc4, 0xac,
	0xd3, 0x37, 0x61, 0x31, 0xa9, 0x6a, 0x3b, 0xf1, 0xa9, 0xd7, 0x44, 0x11, 0xa3, 0xc4, 0x75, 0x3b,
	0xf6, 0x98, 0x33, 0xf3, 0x5d, 0x16, 0x16, 0x8f, 0x51, 0x04, 0x9d, 0x87, 0xe9, 0x5d, 0x1a, 0x71,
	0x8f, 0x85, 0x4a, 0xfd, 0xb9, 0x0e, 0xc8, 0xee, 0xf1, 0x7a, 0x54, 0xcb, 0x3e, 0xbc, 0x8e, 0x63,
	0x97, 0x7c, 0x79, 0x0d, 0x48, 0x24, 0xcf, 0x74, 0x38, 0x0c, 0xba, 0xc9, 0x5d, 0x59, 0xd4, 0xc6,
	0x0d, 0x65, 0x43, 0x9f, 0x43, 0xc1, 0x80, 0xd4, 0x83, 0x2f, 0xa7, 0x2e, 0xfe, 0xf9, 0xd7, 0xa3,
	0x5a, 0x21, 0xb9, 0xf8, 0xaf, 0xb6, 0x31, 0x68, 0x8c, 0x7a, 0x00, 0x3e, 0x81, 0x8a, 0x7e, 0x1c,
	0x1d, 0xf3, 0x40, 0xc9, 0xbf, 0xff, 0x03, 0x45, 0x55, 0x4c, 0x06, 0x9f, 0x52, 0x88, 0x8d, 0xe3,
	0xdf, 0x2a, 0x1c, 0x16, 0xde, 0x98, 0x87, 0x4a, 0x90, 0x35, 0x2f, 0x95, 0x3c, 0xce, 0x7a, 0x2e,
	0x2a, 0x43, 0xce, 0xa7, 0xa1, 0x59, 0xa4, 0x1c, 0xa2, 0x2f, 0x60, 0x7c, 0x1b, 0xab, 0x47, 0xed,
	0xdb, 0x96, 0x37, 0x97, 0xc0, 0xf0, 0xb8, 0xc5, 0xfe, 0x92, 0x85, 0x62, 0x5a, 0xfc, 0xff, 0x8f,
	0xea, 0xe8, 0x3a, 0xcc, 0x1f, 0xa9, 0x30, 0x55, 0x01, 0xc7, 0x50, 0x2c, 0x1d, 0x2e, 0x36, 0x2d,
	0xdd, 0xa5, 0x36, 0xc0, 0xf8, 0x81, 0x8e, 0x8a, 0x30, 0xb3, 0xb5, 0x79, 0xef, 0xee, 0xea, 0xad,
	0xcd, 0x07, 0xe5, 0x0c, 0x02, 0x98, 0xba, 0xfb, 0x70, 0x7b, 0xf5, 0xfe, 0x6a, 0xd9, 0x92, 0x63,
	0xbc, 0xb9, 0xb6, 0xb9, 0xb6, 0x59, 0xce, 0x76, 0xba, 0x2f, 0xf7, 0xab, 0x99, 0x57, 0xfb, 0xd5,
	0xcc, 0x9f, 0xfb, 0xd5, 0xcc, 0xf3, 0x83, 0x6a, 0xe6, 0xc5, 0x41, 0x35, 0xf3, 0xeb, 0x41, 0xd5,
	0x7a, 0x75, 0x50, 0xcd, 0xfc, 0x76, 0x50, 0xcd, 0x3c, 0xbe, 0xd9, 0xf3, 0x44, 0x7f, 0xd8, 0x6d,
	0x38, 0x2c, 0x68, 0x3a, 0x8c, 0x07, 0x8c, 0x37, 0xbd, 0xae, 0xb3, 0xd2, 0x63, 0xcd, 0xdd, 0xab,
	0xcd, 0x80, 0xb9, 0x43, 0x9f, 0x72, 0xfd, 0x1b, 0xb5, 0x12, 0xff, 0x47, 0xb5, 0x5a, 0x2b, 0xfa,
	0x57, 0x4a, 0xec, 0x0d, 0x28, 0xef, 0x4e, 0xa9, 0x8b, 0xf7, 0xea, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x73, 0xc6, 0x08, 0x71, 0x0d, 0x00, 0x00,
}
